# Generated by Django 4.2.6 on 2023-10-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amenity_booking", "0002_alter_amenity_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="amenity",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(verbose_name="End Time"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.TimeField(verbose_name="Start Time"),
        ),
    ]
