# Generated by Django 4.2.6 on 2023-10-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0003_alter_booking_amenity_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
