# Generated by Django 4.2.6 on 2023-11-09 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0008_userprofile_email_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
