# Generated by Django 4.2.7 on 2023-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amenity_booking", "0010_booking_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking", name="end_time", field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="booking", name="start_time", field=models.TimeField(),
        ),
    ]
