# Generated by Django 4.2.6 on 2023-11-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0013_message_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='join_pass',
            field=models.CharField(default='942767', editable=False, max_length=6, unique=True),
        ),
    ]
