# Generated by Django 4.2.6 on 2023-11-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0016_alter_community_join_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='join_pass',
            field=models.CharField(default='829754', max_length=6, unique=True),
        ),
    ]
