# Generated by Django 4.2.7 on 2023-12-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amenity_booking", "0019_alter_community_join_pass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="join_pass",
            field=models.CharField(default="251736", max_length=6, unique=True),
        ),
    ]
