# Generated by Django 4.2.6 on 2023-11-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity_booking', '0007_community_amenity_description_alter_booking_amenity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pass', max_length=128),
            preserve_default=False,
        ),
    ]
